#!/usr/bin/env bash
# Install nginx on your web-01 server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Hello World!" > /var/www/html/index.html
